set(FLAME_PLATFORM Posix)
set(FLAME_STATIC_LIBRARY_SUFFIX ".a")
set(FLAME_SHARED_LIBRARY_SUFFIX ".so")

if(FLAME_THREADING)
	set(CMAKE_FIND_LIBRARY_SUFFIXES ${FLAME_STATIC_LIBRARY_SUFFIX})
	find_library(PTHREAD_STATIC_LIBRARY pthread)
	add_library(PTHREAD_STATIC STATIC IMPORTED ${PTHREAD_STATIC_LIBRARY})
	unset(PTHREAD_STATIC_LIBRARY)

	set(CMAKE_FIND_LIBRARY_SUFFIXES ${FLAME_SHARED_LIBRARY_SUFFIX})
	find_library(PTHREAD_SHARED_LIBRARY pthread)
	add_library(PTHREAD_SHARED SHARED IMPORTED ${PTHREAD_SHARED_LIBRARY})
	unset(PTHREAD_SHARED_LIBRARY)

	set(FLAME_DEPENDENCY_SHARED_LIBRARIES ${PTHREAD_SHARED_LIBRARY})
	set(FLAME_DEPENDENCY_STATIC_LIBRARIES ${PTHREAD_STATIC_LIBRARY})
endif()
