set(FLAME_PLATFORM Posix)

set(FLAME_STATIC_LIBRARY_SUFFIX ".a")
set(FLAME_SHARED_LIBRARY_SUFFIX ".so")

if(FLAME_THREADING)
	list(APPEND FLAME_DEPENDENCY_SHARED_LIBRARIES Threads::Threads)
	list(APPEND FLAME_DEPENDENCY_STATIC_LIBRARIES Threads::Threads)
endif()

if(CMAKE_INSTALL_LIBDIR)
	set(FLAME_PLATFORM_INSTALL_SHARED_DIR ${CMAKE_INSTALL_LIBDIR})
else()
	set(FLAME_PLATFORM_INSTALL_SHARED_DIR lib)
endif()

set(FLAME_PLATFORM_BINARY_INSTALL_TYPE RUNTIME)
set(FLAME_PLATFORM_STATIC_INSTALL_TYPE ARCHIVE)
set(FLAME_PLATFORM_SHARED_INSTALL_TYPE LIBRARY)
