set(FLAME_PLATFORM Posix)

set(FLAME_LIBRARY_PREFIX "lib")
set(FLAME_STATIC_LIBRARY_PREFIX "${FLAME_LIBRARY_PREFIX}")
set(FLAME_SHARED_LIBRARY_PREFIX "${FLAME_LIBRARY_PREFIX}")

set(FLAME_STATIC_LIBRARY_SUFFIX ".a")
set(FLAME_SHARED_LIBRARY_SUFFIX ".so")

set(FLAME_PLATFORM_INSTALL_SHARED_DIR ${CMAKE_INSTAL_LIBDIR})

set(FLAME_PLATFORM_BINARY_INSTALL_TYPE RUNTIME)
set(FLAME_PLATFORM_STATIC_INSTALL_TYPE ARCHIVE)
set(FLAME_PLATFORM_SHARED_INSTALL_TYPE LIBRARY)
