set(FLAME_PLATFORM Windows)

set(FLAME_STATIC_LIBRARY_SUFFIX ".lib")
set(FLAME_SHARED_LIBRARY_SUFFIX ".dll")
set(FLAME_IMPLIB_LIBRARY_SUFFIX
	"${FLAME_SHARED_LIBRARY_SUFFIX}${FLAME_STATIC_LIBRARY_SUFFIX}")

set(FLAME_PLATFORM_INSTALL_HEADER_DIR include)
set(FLAME_PLATFORM_INSTALL_STATIC_DIR lib)
set(FLAME_PLATFORM_INSTALL_SHARED_DIR bin)
set(FLAME_PLATFORM_INSTALL_BINARY_DIR bin)
