set(FLAME_PLATFORM Windows)

set(FLAME_STATIC_LIBRARY_SUFFIX ".lib")
set(FLAME_SHARED_LIBRARY_SUFFIX ".dll")
set(FLAME_IMPLIB_LIBRARY_SUFFIX
	"${FLAME_SHARED_LIBRARY_SUFFIX}${FLAME_STATIC_LIBRARY_SUFFIX}")
