set(FLAME_PLATFORM Windows)

set(FLAME_STATIC_LIBRARY_SUFFIX ".lib")
set(FLAME_SHARED_LIBRARY_SUFFIX ".dll")
set(FLAME_IMPLIB_LIBRARY_SUFFIX
	"${FLAME_SHARED_LIBRARY_SUFFIX}${FLAME_STATIC_LIBRARY_SUFFIX}")

if(CMAKE_INSTALL_BINDIR)
	set(FLAME_PLATFORM_INSTALL_SHARED_DIR ${CMAKE_INSTALL_BINDIR})
else()
	set(FLAME_PLATFORM_INSTALL_SHARED_DIR bin)
endif()

set(FLAME_PLATFORM_BINARY_INSTALL_TYPE RUNTIME)
set(FLAME_PLATFORM_STATIC_INSTALL_TYPE ARCHIVE)
set(FLAME_PLATFORM_SHARED_INSTALL_TYPE RUNTIME)
