include(Functions/CommonFunctions)
include(Functions/CompileBinaryFunctions)
include(Functions/CompileLibraryFunctions)
include(Functions/HeaderLibraryFunctions)
include(Functions/PrintFunctions)
include(Functions/ResolveFunctions)
include(Functions/TargetPropertiesFunctions)
