include(GNUInstallDirs)

if(FLAME_THREADING)
	find_package(Threads REQUIRED)
	if(NOT (TARGET Threads::Threads))
		message(FATAL_ERROR "Target 'Threads::Threads' not found")
	endif()
endif()

if(UNIX)
	include(Platform/Unix)
elseif(WIN32)
	include(Platform/Windows)
else()
	message(FATAL_ERROR "Not supported platform")
endif()

if(CMAKE_INSTALL_INCLUDEDIR AND CMAKE_INSTALL_LIBDIR AND CMAKE_INSTALL_BINDIR)
	set(FLAME_INSTALL_HEADER_DIR ${CMAKE_INSTALL_INCLUDEDIR})
	set(FLAME_INSTALL_STATIC_DIR ${CMAKE_INSTALL_LIBDIR})
	set(FLAME_INSTALL_BINARY_DIR ${CMAKE_INSTALL_BINDIR})
else()
	message_status("Use default settings")
	set(FLAME_INSTALL_HEADER_DIR include)
	set(FLAME_INSTALL_STATIC_DIR lib)
	set(FLAME_INSTALL_BINARY_DIR bin)
endif()
set(FLAME_INSTALL_SHARED_DIR ${FLAME_PLATFORM_INSTALL_SHARED_DIR})
