set(FLAME_FAKE_HEADER_MODULE_SUFFIX hpp
	CACHE STRING "-" FORCE)
set(FLAME_HEADER_MODULE_SUFFIX header
	CACHE STRING "-" FORCE)
set(FLAME_OBJECT_MODULE_SUFFIX object
	CACHE STRING "-" FORCE)
set(FLAME_OBJECT_INDEPENDENT_MODULE_SUFFIX independent
	CACHE STRING "-" FORCE)
set(FLAME_STATIC_MODULE_SUFFIX static
	CACHE STRING "-" FORCE)
set(FLAME_SHARED_MODULE_SUFFIX shared
	CACHE STRING "-" FORCE)
set(FLAME_BINARY_MODULE_SUFFIX binary
	CACHE STRING "-" FORCE)
set(FLAME_CUSTOM_TARGET_SUFFIX property
	CACHE STRING "-" FORCE)

set(FLAME_NAME_SEPARATOR "."
	CACHE STRING "-" FORCE)
set(FLAME_ALIAS_SEPARATOR "::"
	CACHE STRING "-" FORCE)

set(FLAME_OBJECT_INDEPENDENT_ALIASED_MODULE_SUFFIX Independent
	CACHE STRING "-" FORCE)

set(FLAME_SIMPLE_PREFIX "--"
	CACHE STRING "-" FORCE)
set(FLAME_DEBUG_PREFIX "${FLAME_SIMPLE_PREFIX} DEBUG --"
	CACHE STRING "-" FORCE)

set(FLAME_PROJECT_ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR})
set(FLAME_LOCAL_INSTALL_PREFIX ${FLAME_PROJECT_ROOT_PATH}/install)

if (FLAME_CONAN_SUPPORT)
	set(FLAME_LOCAL_INSTALL_CONAN_DIR ${CMAKE_CURRENT_LIST_DIR}/Packaging/_Conan)
endif()

set(FLAME_CONFIG_PATH ${CMAKE_CURRENT_BINARY_DIR}/include/CmakeFlameResolver)
