set(FLAME_NAMESPACE ${PROJECT_NAME})

set(FLAME_FAKE_HEADER_MODULE_SUFFIX hpp)
set(FLAME_HEADER_MODULE_SUFFIX header)
set(FLAME_OBJECT_MODULE_SUFFIX object)
set(FLAME_OBJECT_INDEPENDENT_MODULE_SUFFIX independent)
set(FLAME_STATIC_MODULE_SUFFIX static)
set(FLAME_SHARED_MODULE_SUFFIX shared)
set(FLAME_BINARY_MODULE_SUFFIX binary)
set(FLAME_CUSTOM_TARGET_SUFFIX property)

set(FLAME_NAME_SEPARATOR ".")
set(FLAME_ALIAS_SEPARATOR "::")

set(FLAME_OBJECT_INDEPENDENT_ALIASED_MODULE_SUFFIX Independent)

#if(CMAKE_INSTALL_PREFIX)
#	set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/install)
#	message(FATAL_ERROR "CMAKE_INSTALL_PREFIX = ${CMAKE_INSTALL_PREFIX}")
#endif()
